### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/Slider#2]
1. Шагу можно задавать отрицательные значения.
2. Если у шага установить значение 0, в консоли появится ошибка, при этом значение будет принято и слайдер перестанет работать, надо запретить ввод такого значения. В случае, например, с минимальным и максимальным значением, при указании максимума меньше минимума, в консоли появляется ошибка, само значение не изменяется, но в панели остается введенное значение, подобного также быть не должно.
3. Неправильно отображается значение.
![Peek 2020-09-15 15-08](https://user-images.githubusercontent.com/51824674/93190642-6c5ccc80-f765-11ea-9566-e98809f68852.gif)

**Comment by GrigorenkoSergey** [comment]
Исправил. Неясности по третьему пункту. Теперь отображается правильно, но если ввести в поле значение 3, то бегунок верно подвинется, но при нажатии на кругляш отображается "2", т.е. в соответствии с шагом.  Так правильно, или все-таки он не должен округляться, когда мы вводим значения программно, а не способом перетаскивания?

**Comment by iatsdotfatr** [comment]
1. В смысле, в соответствии с шагом? Подсказка должна отображать ТЕКУЩЕЕ положение бегунка, плюс лучше сделать ее постоянно видимой или добавить такую возможность, сохранив текущую (то есть выбирать, показывать значение только на активном бегунке или постоянно).
То есть подобного быть не должно:
![2 to 3](https://user-images.githubusercontent.com/51824674/93736494-5e45fa80-fc02-11ea-9fb2-cdba3e39b3c2.gif)
![five](https://user-images.githubusercontent.com/51824674/93736499-61d98180-fc02-11ea-8b05-8f84f4333530.gif)

2. Не надо менять правый бегунок на левый, по крайней мере, по умолчанию. Движение просто должно останавливаться.
![lesser to greater](https://user-images.githubusercontent.com/51824674/93736564-92b9b680-fc02-11ea-9fc6-614339298590.gif)

3. И чтобы не возникало проблем с доступностью бегунков после вышенаписанной правки (пункт 2), сам слайдер также надо сделать интерактивным, то есть должна быть возможность перемещать бегунки по клику на слайдер.

4. Почему нельзя вводить условно допустимые значения?
![no valid](https://user-images.githubusercontent.com/51824674/93736711-fa700180-fc02-11ea-971a-5b2a2e24d005.gif)

5. Значения в инпуте дробные, значения в подсказке округляются до целого.
![rounding](https://user-images.githubusercontent.com/51824674/93736819-4de24f80-fc03-11ea-8cba-a1bad0fc0491.gif)

6. Делать неактивным инпут со значением второго бегунка, если он отключен.
![disable](https://user-images.githubusercontent.com/51824674/93736868-79fdd080-fc03-11ea-9c41-3a1cba112fc2.png)

7. В вертикальном положении для удобства должна быть возмножность задавать горизонтальную ориентацию значениям шкалы и подсказки.
![Screenshot from 2020-09-21 12-16-01](https://user-images.githubusercontent.com/51824674/93737174-52f3ce80-fc04-11ea-8d3c-ae15a902dcb0.png)

**Comment by GrigorenkoSergey** [comment]
Полностью переписал на более вменяемую архитектуру.

**Comment by iatsdotfatr** [comment]
1. Полоса слайдера неинтерактивная, нельзя перемещать бегунки по клику на нее.

2. Переключатель не работает.
![no hint](https://user-images.githubusercontent.com/51824674/100572841-ac613380-3300-11eb-9b5f-3d6b72cf5c7d.gif)

3. Нет объединения бегунков при одинаковом значении, что на больших интервалах дает странные результаты. Также программно объединение возможно, что приводит к некорректному наложению значений. То есть, надо разрешить объединение при равных значениях, и корректно отображать наложение.
![connection](https://user-images.githubusercontent.com/51824674/100573265-999b2e80-3301-11eb-8ec7-80b92e549905.gif)
![Peek 2020-11-30 11-14](https://user-images.githubusercontent.com/51824674/100573271-9d2eb580-3301-11eb-825a-9c3be962a331.gif)

4. Если недостаточно места для полного шага, не делать частичный шаг.
![magnet](https://user-images.githubusercontent.com/51824674/100573438-fbf42f00-3301-11eb-864d-988b9240ca45.gif)
 
5. Возможно, хотя и необязательно, лучше ограничивать число делений шкалы в зависимости от ширины/высоты слайдера.
![reasonable limit](https://user-images.githubusercontent.com/51824674/100573714-a3716180-3302-11eb-9a72-4378dab07793.gif)

**Comment by GrigorenkoSergey** [comment]
Исправил. А как я умудрился сделать ссылку выше?!?!?

**Comment by iatsdotfatr** [comment]
> Исправил. А как я умудрился сделать ссылку выше?!?!?

Через решетку и номер, наверное.

1.
![no stop](https://user-images.githubusercontent.com/51824674/100966689-b92b9480-3557-11eb-9f45-3c42c267b946.gif)

2. На слайдер тоже надо добавить cursor: pointer, раз он теперь интерактивный, на бегунках, для различия, можно сделать grab/grabbing.

3. Значения сливаются:

![blur](https://user-images.githubusercontent.com/51824674/100966871-22130c80-3558-11eb-92b7-7685b774729d.png)

Можно, например, сделать так:

![like that](https://user-images.githubusercontent.com/51824674/100966984-5981b900-3558-11eb-8e07-5a9aca5a8c16.gif)

**Comment by iatsdotfatr** [comment]
1. 
![Peek 2020-12-08 14-14](https://user-images.githubusercontent.com/51824674/101458238-d2ba4b00-3960-11eb-9456-80d41df15609.gif)

2. Троеточие не очень, поставь тире (не дефис). Ну и у курсор можно сделать динамическим, как я писал, с grab на grabbing.
![Screenshot from 2020-12-08 14-16-20](https://user-images.githubusercontent.com/51824674/101458321-ee255600-3960-11eb-938a-1f82979ff9cd.png)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
Неподходящий курсор
![bad cursor](https://user-images.githubusercontent.com/51824674/103400072-fa6e8e80-4b6d-11eb-89f7-5d94dfc23c3d.png)

**Comment by GrigorenkoSergey** [comment]
Готово
