### ISSUE TITLE
Common

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/Slider#3]
1. Dist в игнор.
![Screenshot from 2020-12-03 11-15-31](https://user-images.githubusercontent.com/51824674/100969644-9c925b00-355d-11eb-9989-5640fbbab755.png)

2. Поправить форматирование, и лучше явно сделать модулем.
![Screenshot from 2020-12-03 11-23-56](https://user-images.githubusercontent.com/51824674/100970261-c435f300-355e-11eb-9dfe-98894987b2ea.png)

**Comment by iatsdotfatr** [comment]
Пустой файл
![empty](https://user-images.githubusercontent.com/51824674/101954102-bd297780-3c25-11eb-8062-bdd65d6897a2.png)

**Comment by iatsdotfatr** [comment]
1. Нет бэкапа для семейства, и здесь точно нужны две переменные?
![no backup](https://user-images.githubusercontent.com/51824674/102685856-ae3a5a80-420d-11eb-81df-088918808f82.png)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
1. Посмотреть в стандартах бэкапы для семейств шрифтов.

2. Зачем отключать первое правило? Зачем второе?

![Screenshot from 2020-12-24 13-51-30](https://user-images.githubusercontent.com/51824674/103073819-7ad34380-45f2-11eb-85c6-3426a0f8f62f.png)
