### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/Slider#4]
1. Плюсы замени на Number, цикл замени на метод массива (неважно, что он сделает больше итераций).
![+, for](https://user-images.githubusercontent.com/51824674/100970383-fcd5cc80-355e-11eb-803f-5d7df74230cd.png)

2. Возвращаемое выражение или оберни в круглые скобки, или напиши в одну строку.
![braces](https://user-images.githubusercontent.com/51824674/100970464-2d1d6b00-355f-11eb-8497-548c1a68ab04.png)

3. Добавь в линтер конфиг airbnb, сейчас он (линтер) как будто не работает.

**Comment by iatsdotfatr** [comment]
С отступами совсем не очень
![format](https://user-images.githubusercontent.com/51824674/101948118-bc8be380-3c1b-11eb-9e4a-002706bcfa98.png)

**Comment by iatsdotfatr** [comment]
Между правилами должны быть пустые строки, заодно модификатор в элемент убери.
![inside li, format](https://user-images.githubusercontent.com/51824674/102685669-8dbdd080-420c-11eb-9cc0-a18671450f89.png)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
1. Поставь пробелы по внутренним краям объектного типа
![formatting](https://user-images.githubusercontent.com/51824674/103399965-9ba91500-4b6d-11eb-8ac9-ae85ad220e24.png)

2. Лишний пробел
![formatt](https://user-images.githubusercontent.com/51824674/103400026-cf843a80-4b6d-11eb-8d74-3eda07edef7b.png)

**Comment by GrigorenkoSergey** [comment]
Готово.
