### ISSUE TITLE
TS

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/Slider#5]
1. Использовать модификаторы доступа, публичными методы должны быть только тогда, когда это необходимо.
2. Данные не any, а зависят от класса, который наследует от наблюдателя, используй дженерики. Экземпляры самого наблюдателя в твоем случае не создаются, отметь его как абстрактный.
3. В TS интерфейсы через "I" обычно не называют, экспорты лучше не делать по умолчанию без необходимости, позволит избежать ошибок в названии при импортах, это просто к сведению, можно не менять.
![Screenshot from 2020-12-03 11-43-05](https://user-images.githubusercontent.com/51824674/100971528-5212dd80-3561-11eb-83bd-261a7f91ff6c.png)

**Comment by GrigorenkoSergey** [comment]
Все готово.

**Comment by iatsdotfatr** [comment]
1. Несоответствие интерфейсов:
Здесь у тебя обертка принимает any:
![Screenshot from 2020-12-08 14-40-18](https://user-images.githubusercontent.com/51824674/101460501-e0bd9b00-3963-11eb-937c-1507d594ba45.png)

Контроллер почему-то принимает any object, как и модель с вью:
![Screenshot from 2020-12-08 14-40-36](https://user-images.githubusercontent.com/51824674/101460803-414cd800-3964-11eb-9d8c-0847bbfcf5d4.png)

По факту, слайдер не может работать с any опциями, но ты не знаешь, что тебе придет туда, поэтому обертка и контроллер принимают unknown. У модели и вью должны быть конкретные интерфейсы, то есть должно быть видно, какие именно данные они могут принимать. В контроллере unknown данные должны проверяться на соответствие их интерфейсам и корректироваться при необходимости. В модели уже происходит дальнейшая нормализация по типу соотношения максимального-минимального значений и т.п.

2. Модификатор public указывать необязательно, здесь про другие модификаторы
![Screenshot from 2020-12-08 14-54-50](https://user-images.githubusercontent.com/51824674/101461775-92a99700-3965-11eb-857b-bdc27b7f1223.png)

**Comment by iatsdotfatr** [comment]
1. Бесполезный тип, в TS есть аналогичный встроенный. Соседа лучше тоже убрать, как я уже говорил выше)
![useless type](https://user-images.githubusercontent.com/51824674/101949411-c878a500-3c1d-11eb-9ccb-dd459fd05c69.png)

2. Неправильная типизация. В данный метод ты передаешь значения слайдера, который могут быть не только строками и логическими, но и числами, и массивами.
![how hap](https://user-images.githubusercontent.com/51824674/101950265-2b1e7080-3c1f-11eb-862c-6b9bdaf1da1d.png)

3. Type assertions, по возможности, лучше не использовать вообще, даже в очевидных случаях вроде этого, просто добавь проверку
![assertion](https://user-images.githubusercontent.com/51824674/101950448-83ee0900-3c1f-11eb-9f6c-596e4374d317.png)
Убери все as и их аналоги в угловых скобках, как в методе из замечания №2.

4. TS на определенные проверки не реагирует. Но в рекомендуемых type guards все необходимое имеется
![Screenshot from 2020-12-12 03-14-46](https://user-images.githubusercontent.com/51824674/101955663-6ec9a800-3c28-11eb-940f-0cb32ef2f7ad.png)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
1. Тип el может быть, например, boolean? Колбэк точно должен что-то явно возвращать?
![any unknown](https://user-images.githubusercontent.com/51824674/102686098-86e48d00-420f-11eb-99aa-46a3c43ac346.png)

2.  Точно any?
![any?????](https://user-images.githubusercontent.com/51824674/102686197-230e9400-4210-11eb-8468-aa3c4161140e.png)

3. "!" тоже разновидность assertion, или сделай свойство обязательным, или добавь проверки в нужных местах. И y event.target убери assertion, он там вообще не нужен.

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
1. Assertion 

![assertion](https://user-images.githubusercontent.com/51824674/103073433-d6e99800-45f1-11eb-9980-6e2dda4c7a5b.png)

2. Для последовательности указывай возвращаемые значения для каждого метода

![inconsistency](https://user-images.githubusercontent.com/51824674/103073513-f54f9380-45f1-11eb-9c4a-4a272464b2e5.png)

3. Это точно публичное поле?

![private view](https://user-images.githubusercontent.com/51824674/103073617-1fa15100-45f2-11eb-93f8-1ed3ab3cb8a6.png)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
1. Не проще сделать через Omit и Pick?
![omit pick](https://user-images.githubusercontent.com/51824674/103400889-e8421f80-4b70-11eb-9b02-0c248b9dd289.png)

2. Зачем именно здесь типизируются переменные?
![overtype](https://user-images.githubusercontent.com/51824674/103400897-f001c400-4b70-11eb-9f0a-588dfc16be87.png)

**Comment by GrigorenkoSergey** [comment]
Готово.
