### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/Slider#6]
1. IIFE не надо.
![no modules](https://user-images.githubusercontent.com/51824674/101460379-b370ed00-3963-11eb-903f-41ba68f3479c.png)

**Comment by iatsdotfatr** [comment]
1. Props на unknown тоже поменяй.

2. Деструктурируй все, что можно.
![destruct](https://user-images.githubusercontent.com/51824674/101950847-2ad2a500-3c20-11eb-878d-082b858149bf.png)

3. Object.assign замени на spread.
![Screenshot from 2020-12-12 01-57-51](https://user-images.githubusercontent.com/51824674/101950904-4342bf80-3c20-11eb-95f5-11f1393b6666.png)

4. Неиспользуемая переменная.
![useless var](https://user-images.githubusercontent.com/51824674/101953577-c8c86e80-3c24-11eb-9233-d573adaa261c.png)

5. Вынеси в методы.
![methods](https://user-images.githubusercontent.com/51824674/101953663-f31a2c00-3c24-11eb-92c1-f1b688b8bace.png)

6. Посмотри стандарты именования jquery, цифры в именах использовать не надо, сокращения имен тоже делать не надо, кроме общепринятых.
![jquerynaming](https://user-images.githubusercontent.com/51824674/101953794-370d3100-3c25-11eb-95a0-29603d73db77.png)
![shortening](https://user-images.githubusercontent.com/51824674/101953808-3d031200-3c25-11eb-8805-0babc40a8ede.png)

7. Есть еще конструкция switch, со своими особенностями. Можно и с Object.keys ее использовать, можно без.
![Screenshot from 2020-12-12 01-55-33](https://user-images.githubusercontent.com/51824674/101954064-ab47d480-3c25-11eb-8c61-18f205bb39f7.png)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
1. Еще assign
![assign](https://user-images.githubusercontent.com/51824674/102685728-df665b00-420c-11eb-8162-84484b0208fa.png)

2. Здесь тоже деструктурируй (без использования вложенной деструктуризации).
![destr](https://user-images.githubusercontent.com/51824674/102685759-1472ad80-420d-11eb-8723-87fb4adf3fde.png)

3. Не надо var
![Screenshot from 2020-12-19 13-56-36](https://user-images.githubusercontent.com/51824674/102685840-86e38d80-420d-11eb-9b7a-6f58f44f5a8a.png)

4.
![Screenshot from 2020-12-19 15-22-06](https://user-images.githubusercontent.com/51824674/102685898-08d3b680-420e-11eb-939c-b6d06eeaa061.png)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
1. Зачем view занимается какой-то валидацией данных? Он должен их просто отображать.

![view val](https://user-images.githubusercontent.com/51824674/103074083-0fd63c80-45f3-11eb-93e8-bbe98b9ec3d4.png)

2. Просто 0.

![0](https://user-images.githubusercontent.com/51824674/103074145-36947300-45f3-11eb-957a-ec2b0735a573.png)

3. classList.

![classlist](https://user-images.githubusercontent.com/51824674/103074229-62175d80-45f3-11eb-9962-22914375d2ff.png)

4. Про "легковесный" конструктор не забывай.

![lw constr](https://user-images.githubusercontent.com/51824674/103074287-807d5900-45f3-11eb-91c2-c8dab5a25535.png)

5. В целом, скрывать и показывать элементы надо с помощью переключения классов, через js меняется только динамика. Но данном случае надо просто убирать элементы из DOM.

![mount unmount](https://user-images.githubusercontent.com/51824674/103074508-ef5ab200-45f3-11eb-9cbf-fc4ce123fddb.png)

6. Почему бы прямо не обращаться к style?

![Screenshot from 2020-12-24 13-28-52](https://user-images.githubusercontent.com/51824674/103074631-3ea0e280-45f4-11eb-8280-a5518ffd7689.png)

7. В данном случае, действительно, не стоит).

![Screenshot from 2020-12-24 13-56-24](https://user-images.githubusercontent.com/51824674/103074691-59735700-45f4-11eb-90ea-0d76cb9bd3e5.png)

8. Зачем вот это всё?

![Screenshot from 2020-12-24 14-05-35](https://user-images.githubusercontent.com/51824674/103074742-73ad3500-45f4-11eb-8d85-97e729163186.png)
![Screenshot from 2020-12-24 14-05-43](https://user-images.githubusercontent.com/51824674/103074753-7871e900-45f4-11eb-8d62-b1deb2d899ec.png)

Объявляй методы-колбэки как стрелочные функции, bind используй только тогда, когда надо привязать какой-то аргумент.

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
1. Методы теперь надо переименовать.
![rename](https://user-images.githubusercontent.com/51824674/103400162-49b4bf00-4b6e-11eb-94c4-eef855a641da.png)

2. Здесь тоже переделать и переименовать.
![remove](https://user-images.githubusercontent.com/51824674/103400295-cb0c5180-4b6e-11eb-9524-95ccedebed92.png)

3. С маленькой буквы
![naming](https://user-images.githubusercontent.com/51824674/103400183-5df8bc00-4b6e-11eb-9a91-5e5f6caca5a6.png)

4. Метод возвращает undefined, поэтому вместо пустого return, можно возвращать сам метод
![return](https://user-images.githubusercontent.com/51824674/103400261-a3b58480-4b6e-11eb-8e51-cf869d06f914.png)

5. Привести к единообразию
![typeof](https://user-images.githubusercontent.com/51824674/103400330-ea0ae380-4b6e-11eb-806e-5ecc404a1f53.png)
![typeof no](https://user-images.githubusercontent.com/51824674/103400335-ec6d3d80-4b6e-11eb-9d99-2a7d63081e9e.png)

6. Неочевидное значение, лучше undefined, и его же и вернуть.
![undeff](https://user-images.githubusercontent.com/51824674/103400380-0eff5680-4b6f-11eb-80f4-e34b4c577583.png)

7. У презентера нет никаких опций, не надо вводить в заблуждение. И не надо в файле с названием types объявлять
 не типы.
![presopts](https://user-images.githubusercontent.com/51824674/103400430-3bb36e00-4b6f-11eb-9358-a10b9196db43.png)
![types const](https://user-images.githubusercontent.com/51824674/103400693-428eb080-4b70-11eb-828d-28038558af4e.png)

8. Дефолтный конфиг лучше вынести в отдельный файл.
![default config](https://user-images.githubusercontent.com/51824674/103400482-68678580-4b6f-11eb-8aa6-7a60b7770d9a.png)

9. Лучше заменить негативное условие на позитивное и написать код внутри блок, тогда и ошибку выбрасывать не придется, к тому же в данном случае она никогда не произойдет
![positive inside block](https://user-images.githubusercontent.com/51824674/103400516-9b117e00-4b6f-11eb-9f20-18c31b3816a3.png)

10. Убрать сокращения, по всему проекту (оставить можно только min и max).
![shorten](https://user-images.githubusercontent.com/51824674/103400608-e9bf1800-4b6f-11eb-8381-df974608d00e.png)

11.  Зачем выполнять какие-то лишние действия? Сразу итерируй ключи переданного объекта, и если есть нужные совпадения, добавляй их куда надо.
![Screenshot from 2020-12-31 13-35-39](https://user-images.githubusercontent.com/51824674/103400810-b16c0980-4b70-11eb-86c5-21a5479caa47.png)

**Comment by GrigorenkoSergey** [comment]
Готово.
