### ISSUE TITLE
BEM

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/Slider#7]
БЭМ никто не отменял, поэтому никакого позиционирования блоков, один блок - один миксин - один препроцессорный файл и т.д.
![block positioning](https://user-images.githubusercontent.com/51824674/101944657-45545080-3c17-11eb-8f5c-d24b66993a38.png)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
Получилось два элемента без блока. Можно добавить по классу для каждого, но лучше js-префикс добавлять только на блок, а внутри блока выбирать нужный элемент уже без префикса.
![no element](https://user-images.githubusercontent.com/51824674/102686326-19d1f700-4211-11eb-94e4-f60962b26c40.png)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
Это один элемент.
![el with mod](https://user-images.githubusercontent.com/51824674/103073959-cc7bce00-45f2-11eb-9ac8-744d8910fedf.png)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
1. left и right key-value
![key value](https://user-images.githubusercontent.com/51824674/103399912-6e5c6700-4b6d-11eb-9e15-1eb7bb6eb3f4.png)
