### ISSUE TITLE
User defined type guards.

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/Slider#8]
Удалить и использовать, как я уже писал, стандартные type guards. User defined type guards используются в специфических случаях при работе с определенными type aliases, и неправильно закодированный type guard приведет к ошибкам.
Например, вот этот закодирован неправильно, и делает совсем не те выводы, которые ты ожидаешь (см. что такое тип Object).
![object Object unknown](https://user-images.githubusercontent.com/51824674/102685477-1a678f00-420b-11eb-8711-4c5a36186da3.png)

Можно написать любой type predicate, и получить соответствующий результат:
![Screenshot from 2020-12-19 15-02-09](https://user-images.githubusercontent.com/51824674/102685537-9c57b800-420b-11eb-9c77-30816a3ba6f8.png)

Поэтому удалить и использовать стандартные, для работы с встроенными JS-типами их достаточно.

**Comment by GrigorenkoSergey** [comment]
Готово.
