### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by iatsdotfatr** [GrigorenkoSergey/Slider#9]
1. Зачем сразу перед удалением элемента удаляется его содержимое?
![Screenshot from 2021-01-15 11-43-37](https://user-images.githubusercontent.com/51824674/104691520-9b457800-5730-11eb-9848-35bac571f4eb.png)

2. Лучше через classList
![Screenshot from 2021-01-15 11-43-45](https://user-images.githubusercontent.com/51824674/104691592-b912dd00-5730-11eb-884d-415c82d30b56.png)

3. Непонятно, к чему относится комментарий. Если к покрытию, то лучше поставить комментарий над покрытием или на той же строке правее. И лучше по умолчанию раскомментировать.
![Screenshot from 2021-01-15 11-48-25](https://user-images.githubusercontent.com/51824674/104691811-20c92800-5731-11eb-9def-18079d194993.png)

4. Цикл завершится без выполнения тела.
![Screenshot from 2021-01-15 11-57-59](https://user-images.githubusercontent.com/51824674/104691958-53732080-5731-11eb-88c7-3ee84424f8f1.png)

5. Почему в одном случае используется getElementsByClassName, в другом querySelector?
![Screenshot from 2021-01-15 12-05-06](https://user-images.githubusercontent.com/51824674/104692068-81f0fb80-5731-11eb-8a8e-201f9fb85bb4.png)

6. Лучше, чтобы везде было options.
![Screenshot from 2021-01-15 12-07-41](https://user-images.githubusercontent.com/51824674/104692104-96cd8f00-5731-11eb-8f4c-89b822e18e95.png)
![Screenshot from 2021-01-15 12-36-49](https://user-images.githubusercontent.com/51824674/104692114-9cc37000-5731-11eb-8946-e8cf0ead8449.png)

7. Вроде бы элементы теперь удаляются, лучше сделать условие проверки более подходящим.
![Screenshot from 2021-01-15 12-10-12](https://user-images.githubusercontent.com/51824674/104692197-c41a3d00-5731-11eb-9ea3-1b5fb43c1495.png)

8. Функцию лучше объявлять до использования.
![Screenshot from 2021-01-15 12-18-41](https://user-images.githubusercontent.com/51824674/104692261-e1e7a200-5731-11eb-9af2-cfb413e0dc9e.png)

9. Метод append может принимать любое количество аргументов.
![Screenshot from 2021-01-15 12-37-03](https://user-images.githubusercontent.com/51824674/104692319-fb88e980-5731-11eb-9ed3-1010629fa0ea.png)

10. Зачем вводятся непонятные значения?
![Screenshot from 2021-01-15 12-49-01](https://user-images.githubusercontent.com/51824674/104692461-3db22b00-5732-11eb-97f4-a72091b0e005.png)

11. Неинформативное описание тестов.
![Screenshot from 2021-01-15 11-46-00](https://user-images.githubusercontent.com/51824674/104692517-53bfeb80-5732-11eb-8463-cff768cecbab.png)
![Screenshot from 2021-01-15 12-39-00](https://user-images.githubusercontent.com/51824674/104692524-57537280-5732-11eb-976c-60a25faeb80c.png)

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by GrigorenkoSergey** [comment]
Готово.

**Comment by iatsdotfatr** [comment]
1. Тесты продолжают падать:
![Screenshot from 2021-01-19 12-36-19](https://user-images.githubusercontent.com/51824674/104997235-73695380-5a53-11eb-9a12-46dfe478c668.png)
![Screenshot from 2021-01-19 12-36-32](https://user-images.githubusercontent.com/51824674/104997240-76644400-5a53-11eb-8f40-fb2dc2b80984.png)

2. Из предыдущего:
![Screenshot from 2021-01-19 12-38-31](https://user-images.githubusercontent.com/51824674/104997148-4ae15980-5a53-11eb-9e34-cda679892ed7.png)

3. Опечатки исправить.
![Screenshot from 2021-01-19 12-04-43](https://user-images.githubusercontent.com/51824674/104997292-8e3bc800-5a53-11eb-917f-c0a95e14be41.png)

4. Одно описание на английском, другое на русском
![Screenshot from 2021-01-19 12-07-44](https://user-images.githubusercontent.com/51824674/104997348-a7dd0f80-5a53-11eb-8a28-0d7d966c1610.png)

5. Несоответствие описания действиям, которые предполагают, что ты и так знаешь значения свойств
![Screenshot from 2021-01-19 12-15-04](https://user-images.githubusercontent.com/51824674/104997524-ea9ee780-5a53-11eb-8786-e8bf25afd3f4.png)

6. Зачем здесь проверяются значения min и max?
![Screenshot from 2021-01-19 12-16-15](https://user-images.githubusercontent.com/51824674/104997623-13bf7800-5a54-11eb-924e-a2eccf36d4cf.png)

7. Что такое "правый диапазон"?
![Screenshot from 2021-01-19 12-20-21](https://user-images.githubusercontent.com/51824674/104997667-2d60bf80-5a54-11eb-98b1-a9cd854d6b7e.png)

8. Подсказки и т.п. это зона ответственности презентера?
![Screenshot from 2021-01-19 12-30-25](https://user-images.githubusercontent.com/51824674/104997735-51240580-5a54-11eb-8683-88169c8c3909.png)
